# Diabetes Dataset Advanced Analysis

This notebook covers advanced data science and AI techniques for the Multiclass Diabetes Dataset.

## Table of Contents
1. Data Loading & Preprocessing
2. Exploratory Data Analysis (EDA)
3. Ensemble Models
4. Hyperparameter Tuning
5. Feature Importance & Selection
6. Model Explainability (SHAP, LIME)
7. Deep Learning Model
8. AutoML
9. Conclusions

In [1]:
import pandas as pd

In [2]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv('../Multiclass_Diabetes_Dataset.csv')
df.head()

   Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  Class
0       0   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0      0
1       1   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0      0
2       1   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0      0
3       0   45   2.3  24    4.0   2.9  1.0  1.0  1.5   0.4  21.0      0
4       0   50   2.0  50    4.0   3.6  1.3  0.9  2.1   0.6  24.0      0